modules/paciente/controllers/CadastroController.php
<?php

namespace app\modules\paciente\controllers;

use Yii;
use app\modules\paciente\models\Paciente;
use app\modules\paciente\models\PacienteSearch;
use app\models\PermissaoEnum;
use app\models\Usuario;
use app\modules\paciente\models\PacienteDocumento;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;


class CadastroController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['view', 'atualizar', 'findmodel', 'alterarsenha', 'validatepostdata'],
                        'roles' => [PermissaoEnum::PACIENTE],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['novo', 'esquecisenha', 'validatepostdata'],
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Paciente models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PacienteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Paciente model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Paciente model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionNovo()
    {
        $model = new Paciente();
        $usuario = new Usuario();
        $model->setScenario(Paciente::SCENARIO_DEFAULT);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            $trans = Yii::$app->db->beginTransaction();

            try {
                $usuario->login = $model->cpf;
                $usuario->permissao = PermissaoEnum::PACIENTE;
                $usuario->save(false);
                $model->usuario_id = $usuario->id;
                $model->save(false);
                $model->sendInfoInsertCheckup();

                Yii::$app->session->setFlash('success', "Usuário cadastrado com sucesso. Efetue login para realizar seu agendamento.");
                $trans->commit();
                return $this->redirect(['/paciente/default/login']);
            } catch (\Exception $e) {
                $trans->rollBack();
                throw $e;
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Paciente model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionAtualizar($id)
    {
        $model = $this->findModel($id);
        $model->setScenario(Paciente::SCENARIO_UPDATE);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            $model->sendInfoInsertCheckup();
            Yii::$app->session->setFlash('success', "Dados atualizados com sucesso.");
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Paciente model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Paciente model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Paciente the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Paciente::findOne((int) $id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionEsquecisenha()
    {

        $model = new Usuario();
        $model->setScenario(Usuario::SCENARIO_FORGOT_PASSWORD);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            $usuario = Usuario::find()->where(['login' => $model->login, 'permissao' => PermissaoEnum::PACIENTE])->one();
            if (!$usuario) {
                Yii::$app->session->setFlash('error', 'Usuário não encontrado!');
                $this->refresh();
                return;
            }

            $senha = $usuario->generatePass();
            $usuario->setScenario(Usuario::SCENARIO_FORGOT_PASSWORD);
            $trans = Yii::$app->db->beginTransaction();

            try {
                if ($usuario->validate()) {
                    $usuario->save();
                    /*&& $usuario->enviarSenhaEmail($usuario->paciente->email, $senha)*/
                    $trans->commit();
                    Yii::$app->session->setFlash('success', 'Senha enviada para o email cadastrado!');
                } else {
                    print_r($usuario->errors);
                    die;
                    $trans->rollBack();
                    Yii::$app->session->setFlash('error', 'Atenção! Ocorreu um problema durante a requisição, tente novamente mais tarde!');
                }
            } catch (\Exception $e) {
                $trans->rollBack();
                throw $e;
            }

            return $this->redirect(['default/login']);
        } else {
            return $this->render('forgot_password', [
                'model' => $model
            ]);
        }
    }

    public function actionAlterarsenha()
    {

        $model = Usuario::findOne(Yii::$app->user->id);
        $model->setScenario(Usuario::SCENARIO_UPDATE_PASSWORD);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            Yii::$app->session->setFlash('success', 'Senha alterada com sucesso!');
            return $this->redirect(['default/index']);
        } else {
            return $this->render('update_password', [
                'model' => $model,
            ]);
        }
    }

    public function actionValidatepostdata()
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $response = ['success' => 0, 'errors' => null];
        $model = new Paciente();

        if (Yii::$app->request->post()['Paciente']['id']) {
            $model = $this->findModel(Yii::$app->request->post()['Paciente']['id']);
            $model->setScenario(Paciente::SCENARIO_UPDATE);
        }

        $model->load(Yii::$app->request->post());

        if ($model->validate()) {
            $response['success'] = 1;
        } else {
            foreach ($model->getErrors() as $value) {
                $response['errors'][] = $value;
            }
        }
        return $response;
    }
}

modules/paciente/controllers/DefaultController.php
<?php

namespace app\modules\paciente\controllers;

use app\models\Log;
use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\PermissaoEnum;
use app\models\Usuario;

/**
 * Default controller for the `paciente` module
 */
class DefaultController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],

        ];
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        $model->role = PermissaoEnum::PACIENTE;
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $model->loginLog();
            $user = Usuario::findOne(Yii::$app->user->identity->id);
            if ($user->isFirstLogin()) {
                return $this->redirect(['cadastro/alterarsenha']);
            }
            return $this->goHome();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionPartiallogin()
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $response = ['success' => 0, 'errors' => null];

        $model = new LoginForm();
        $model->role = PermissaoEnum::PACIENTE;
        $model->load(Yii::$app->request->post());

        if ($model->validate()) {
            $model->login();
            $response['success'] = 1;
        } else {
            foreach ($model->getErrors() as $value) {
                $response['errors'][] = $value;
            }
        }

        $model->password = '';
        return $response;
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

modules/paciente/views/default/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you. 88
    </p>

</div>

modules/paciente/views/default/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Sistema de Pré-agendamento Checkup';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Bem vindo ao Sistema de Pré-agendamento do Hospital Checkup!</h1>

        <p class="lead">Escolha o serviço desejado abaixo.</p>

    </div>

    <div class="body-content">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="panel panel-index admin">
                    <div class="panel-heading">
                        <h3>Exame</h3>
                    </div>
                    <div class="panel-body">
                        <p>Marcação de exames</p>
                        <p><a class="btn btn-default" href="/paciente/agendamentoexame/novo">Pré-agendar &raquo;</a></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="panel panel-index paciente">
                    <div class="panel-heading">
                        <h3>Consulta</h3>
                    </div>
                    <div class="panel-body">
                        <p>Marcação de consultas</p>
                        <p><a class="btn btn-default" href="/paciente/agendamentoconsulta/novo">Pré-agendar &raquo;</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

modules/paciente/views/default/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<h1 class="text-center"><?= Html::encode($this->title) ?></h1>
<br>

<div class="site-login col-lg-offset-3 col-lg-6 col-lg-offset-3">

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
    ]); ?>
    <?= $form->field($model, 'username')->widget(\yii\widgets\MaskedInput::className(), [
        'mask' => '999.999.999-99'
    ]) ?>
    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe')->checkbox() ?>

    <div class="form-group text-center">
        <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        <?= Html::a('Esqueci a senha', ['cadastro/esquecisenha'], ['class' => 'btn btn-danger', 'name' => 'login-button']) ?>

    </div>

    <?php ActiveForm::end(); ?>

    <p class="text-danger text-center">Caso não possua cadastro, clique em: <?= Html::a('Efetuar Cadastro', ['cadastro/novo']) ?>

</div>